### ISSUE TITLE
A lot enhancement features

### ISSUE THREAD

**Issue by KriszXD** [sporrus/randomMindustry#18]
As the title suggests I will list a few nice additions that could be added:

## **Power category**

- [ ] More things should require power but power also should be more accessible
- [x] Factories needing power too, sometimes only needing power to function
- [x] Thorium reactor needing random item and coolant
- [x] Impact reactor needing random item and coolant
- [ ] Thermal generator needing random tiles with random efficiency
- [ ] Since things like arc and lancer have random power usage factories (both unit and normal), phase conveyors and mass drivers, the different power using drills etc. should use random amounts of power too
- [X] Random power generation (maybe to make the power not too random you could set a random number generator and take the sqrt of the number to make very high numbers hard to get, tho the max number generated could be different for the different power generators) almost
 
## **A few misc building related things**

- [ ] Mender, mend projector, force projector, overdrive projector and overdrive dome should use random items as boosters
- [ ] The effect of the previously listed blocks could be randomized (as in like effectiveness of boosters, mending speed, overdrive %, shield hp) 
- [ ] Make unloader a bit more accessible

## **Drills**

- [ ] Drills should use a random booster
- [ ] Drills should use a random amount of the booster
- [ ] The booster should increase the drill speed by a random amount
- [ ] Oil extractor being randomized
- [ ] Water extractor drilling at random speed and a random liquid (or could drill a booster shared among all the drills)

## **Turrets / units**

- [x] Limit the particle size so no flashbangs / remove the flashbanging particles
- [ ] Make monos mine the basic materials (the materials that you can normally mine)
- [ ] Make segment not lame

## **Pumps and stuff**

- [ ] Make the pumping speed random (tho every pump should maybe get a multiplier so a single pump cant pump faster than a 2x2 one)
- [ ] Make the water / oil / slag random just like the other ores

## **The factory thing I forgor their name 💀**

- [ ] Make cryofluid mixer, spore press and melter give random amounts of liquid and a random liquid
- [ ] Disassembler and separator should accept random inputs and give random outputs

## **A few general stuff**

- [ ] Make the affinities random (random blocks and random %, things like cultivator use these)
- [X] Make very high liquid usage rare
- [X] Add an epilepsy warning to the mod description
- [ ] Have fun trying to add most of these

**Comment by gorodmi** [comment]
the...

**Comment by Mythril382** [comment]
good lord

**Comment by gorodmi** [comment]
time to work on this :skull:

**Comment by Mythril382** [comment]
this suggestion will be closed due to random mindustry's ultimate rewrite
