### ISSUE TITLE
Tints unrender for some cases with certain actions

### ISSUE THREAD

**Issue by BlueWolf3682** [sporrus/randomMindustry#28]
after placing a unit factory, the items untinted: 
![image](https://user-images.githubusercontent.com/61173114/194736498-7be022a5-1d75-4de7-9cbf-62663a8a7ea0.png)
later, block icons also untinted: 
![image](https://user-images.githubusercontent.com/61173114/194736516-9030d3f2-0c5a-499e-b943-2239166a77da.png)

mod build: latest mod browser release 
save: [spiggity sparrow i encountered an error](https://github.com/sporrus/randomMindustry/files/9740700/spetty.zip)
generation seed: 6289539263406523259

**Comment by gorodmi** [comment]
ui icons somehow untinted :zombie: 
regenerate with the same seed to get everything tinted again
dont know why it untints

**Comment by BlueWolf3682** [comment]
(this does not apply to the new branch)
