### ISSUE TITLE
direct repair with non-homing bullets doesn't work

### ISSUE THREAD

**Issue by kapzduke** [sporrus/randomMindustry#40]
![image](https://user-images.githubusercontent.com/60543005/221425467-c13f247d-4a37-49a1-87d0-31d8bef8cc28.png)
![image](https://user-images.githubusercontent.com/60543005/221425444-203a19c0-2e6f-4ed0-bcc7-a410f09d5a82.png)
![image](https://user-images.githubusercontent.com/60543005/221425525-9b73fad1-4dd6-4eeb-b02e-9f6fe5618ea6.png)

https://user-images.githubusercontent.com/60543005/221425605-22347f03-8612-47c3-b247-b2c39a0a968c.mp4

**Comment by kapzduke** [comment]
i feel like the previous code for bullets was better

**Comment by Mythril382** [comment]
Weird, I'll try fixing this bug, if I can.

**Comment by Mythril382** [comment]
Should be fixed in v2.0.1-alpha but I'm not sure...
