### ISSUE TITLE
A very minor enhancing suggestion post

### ISSUE THREAD

**Issue by KriszXD** [sporrus/randomMindustry#42]
- ### 1. Names
First of all having names like  `random-mindustry-random-core-0` sounds uh.... well I'd say interesting, so you could instead add a few randomised names
Tier 0 could be like:
```
 Shardite
 Emberite
 Planto
 Crystalline
 Addus
 Scrapforge
 Foundryite
 Defendium
 Spark
 Routstem
```
TIer 1: 
```
 Hydrolune
 Pyrocore
 Enerforge
 Stonewarden
 Voltaicor
 Mechanorium
 Refinecore
 Electroflux
 Armamentium
 Alloyvault
```
Tier 2:
```
Reactorium
Corefinity
Plasmatrix
Fusionium
Luminoth
Megafactory
Energyspire
Defenseus
Extractorium
Technohearth
```
TIer 3:
```
Omniforge
Quantumexus
Titanheart
Fortiplex
Ascendium
Plasmatica
Exponentium
Technoplasma
Innovatrix
Quantumium
```
You could additionally add a randomiser for names which could be referring to the names of the materials used, for example you could use the highest tier material as a name, adding some text to it, not making it bland, for example from mezium to Mezonilt
The planet could also have some named sectors, at least the first one
- ### Actual changes
- ### 1) Units
This might be obvious, but units would be cool to add to the game, maybe with not only 3 types of bbase factories, I won't really post a lot of detail here, since I think it was already planned
- ### 2) Fixing transport
Uh, currently there are a lot of missing blocks, such as junctions, over/underflow gates and sorters, they are really useful and I think they should be implemented in some form
You could also add plastanium conveyors, changing the capacity and speed of them (if that's possible) to add a bit more fresh feeling to the methods of transport in the game
- ### 3) Power.
There is no system for power in the mod, which would be cool, because the nodes could have various sizes, max connections, and ranges, also a lot of different power supply generator options, and a lot of things could use power as their fuel or partial fuel
Maybe factories which only need power to function, also if units were added I think this should also go along with it
- ### 4) Liquids
I think this was also already planned so I will keep this section short, but there could be a lot of cool features you could add uing liquids, such as for turrets, coolant, or fuel, similarly to the current items, these could also have their tiers, and effectiveness
They could be accessible using factories, or drills, which could work similarly to water extractors or oil extractors, having required or efficient tiles
- ### 5) Better progression
In the first sector already there are way more resources, than actually accessible, and by that I mean that, by the time you reach wave 10 you could only get so many resources, and you could just get like basically the entire research tree from the first sector if you were patient enough, I think there should be resource limitations for the first few sectors or sector requirements for certain branches in the research tree, which would work really well alongside the named sectors feature
- ### 6) Too many ores
Already in the first sector, there is a huge quantity of ores, most of them not even accessible until quite a bit of time, making the map feel cluttered and have less space
- ### 7) Sand and scrap have 0 use
They should have a use or should be completely removed from spawningp (you are welcome)

**Comment by Mythril382** [comment]
The name `random-mindustry-random-core-0` sure is fascinating, but it's just a temporary name! Who knows, we might change it to what you suggested, or we might change it in our own ways!

**Comment by Mythril382** [comment]
As for other stuff, v2 is in alpha, and thus isn't finished yet. We just need feedback on the current content or something ~~idk~~. But, I'm sure we'll add those soon!

**Comment by Mythril382** [comment]
I forgot to close.
